plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/opt/build/repo/src/frontend/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "pnpm --filter @caffeine/template-frontend... run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]